/**
 * MathWorks MATLAB terminal integration.
 *
 * Detects whether the MathWorks VS Code extension is installed, opens the
 * MATLAB command window, and sends commands to it.
 */

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import * as vscode from 'vscode';

/**
 * Check whether the MathWorks MATLAB extension is installed.
 */
export function isMatlabExtensionAvailable(): boolean {
  return vscode.extensions.getExtension('MathWorks.language-matlab') !== undefined;
}

/**
 * Send a command string to the MathWorks MATLAB terminal.
 *
 * The MathWorks pseudoterminal reliably routes short single-line sendText
 * payloads (e.g. typed-by-human commands) but silently drops the multi-line
 * script generated by scistack_gui.api.matlab_command — nothing appears in
 * the MATLAB terminal and the commands never reach the MATLAB engine. As a
 * result, addpath/configure_database/for_each never execute and any
 * breakpoint set on the target function never fires.
 *
 * We work around this by writing the full script to a temp ``.m`` file and
 * sendText-ing a one-line ``run('<path>')``. That single short call is
 * delivered reliably by the pseudoterminal.
 *
 * @returns true if the command was dispatched, false if the terminal is
 *          unavailable (caller falls back to clipboard).
 */
export async function runInMatlabTerminal(
  command: string,
  outputChannel?: vscode.OutputChannel,
): Promise<boolean> {
  if (!isMatlabExtensionAvailable()) {
    return false;
  }

  try {
    // Stable filename (overwritten each invocation) so we don't clutter
    // the temp dir. `run` evaluates the script in the caller's workspace,
    // so variables defined in the script remain visible after it returns.
    const scriptPath = path.join(os.tmpdir(), 'scistack_run.m');
    fs.writeFileSync(scriptPath, command, 'utf-8');
    outputChannel?.appendLine(
      `runInMatlabTerminal: wrote ${command.length}-char script to ${scriptPath}`,
    );

    // The MathWorks extension provides this command to open the MATLAB
    // command window as an integrated terminal.
    await vscode.commands.executeCommand('matlab.openCommandWindow');

    // Find the MATLAB terminal (created by the MathWorks extension).
    const terminal = vscode.window.terminals.find(t => t.name === 'MATLAB');
    if (!terminal) {
      outputChannel?.appendLine(
        'MathWorks extension found but MATLAB terminal not available.'
      );
      return false;
    }

    // MATLAB accepts forward slashes on Windows; converting avoids having
    // to escape backslashes inside the single-quoted string literal.
    const forMatlab = scriptPath.replace(/\\/g, '/');
    const runLine = `run('${forMatlab}');`;
    outputChannel?.appendLine(`runInMatlabTerminal: sendText ${runLine}`);
    terminal.sendText(runLine);
    terminal.show();
    return true;
  } catch (err) {
    outputChannel?.appendLine(`Failed to send to MATLAB terminal: ${err}`);
    return false;
  }
}
