"""
Generate ready-to-paste MATLAB commands for running pipeline functions.

The generated script configures the database, registers variable types,
and calls ``scihist.for_each`` with the correct inputs, outputs, and
schema arguments — all formatted as MATLAB syntax.
"""

import logging
from pathlib import Path

logger = logging.getLogger(__name__)


def generate_matlab_command(
    function_name: str,
    db_path: str,
    schema_keys: list[str],
    variants: list[dict] | None = None,
    schema_filter: dict[str, list] | None = None,
    schema_level: list[str] | None = None,
    addpath_dirs: list[str] | None = None,
) -> str:
    """Generate a complete MATLAB script to run a pipeline function.

    Parameters
    ----------
    function_name
        Name of the MATLAB function to run (e.g. ``"bandpass_filter"``).
    db_path
        Absolute path to the .duckdb file.
    schema_keys
        Dataset schema keys (e.g. ``["subject", "session"]``).
    variants
        List of variant dicts from the DAG. Each variant has keys:
        ``input_types``, ``output_type``, ``constants``, ``record_count``.
        If empty/None, generates a template command.
    schema_filter
        Optional ``{key: [selected_values]}`` for filtering.
    schema_level
        Optional list of schema keys to iterate over.
    addpath_dirs
        Optional list of directories to add to MATLAB path.

    Returns
    -------
    str
        A complete, self-contained MATLAB script.
    """
    lines: list[str] = []
    lines.append(f"%% SciStack: Run {function_name}")
    lines.append("% Generated by SciStack GUI — paste into MATLAB Command Window")
    lines.append("")

    # addpath entries
    if addpath_dirs:
        for d in addpath_dirs:
            lines.append(f"addpath('{_escape_matlab_string(d)}');")
        lines.append("")

    # Configure database
    schema_keys_str = _format_matlab_string_array(schema_keys)
    lines.append("% Configure database (skip if already configured)")
    lines.append(
        f"db = scihist.configure_database('{_escape_matlab_string(db_path)}', "
        f"{schema_keys_str});"
    )
    lines.append("")

    if not variants:
        # No variant info — generate a template.
        lines.append(f"% Run (fill in inputs/outputs)")
        lines.append(f"scihist.for_each(@{function_name}, ...")
        lines.append(f"    struct(), ...")  # inputs placeholder
        lines.append(f"    {{}});")         # outputs placeholder
        return "\n".join(lines)

    # Collect all variable types referenced across all variants.
    all_var_types: set[str] = set()
    for v in variants:
        input_types = v.get("input_types", {})
        if isinstance(input_types, dict):
            all_var_types.update(input_types.values())
        output_type = v.get("output_type", "")
        if output_type:
            all_var_types.add(output_type)

    # Register variable types
    if all_var_types:
        lines.append("% Register variable types")
        for vtype in sorted(all_var_types):
            lines.append(f"scidb.register_variable('{vtype}');")
        lines.append("")

    # Deduplicate variants by constants (same logic as run.py).
    seen_constants: set[tuple] = set()
    unique_variants: list[dict] = []
    for v in variants:
        key = tuple(sorted(v.get("constants", {}).items()))
        if key not in seen_constants:
            seen_constants.add(key)
            unique_variants.append(v)

    # Generate for_each call for each unique variant.
    for v in unique_variants:
        input_types = v.get("input_types", {})
        output_type = v.get("output_type", "")
        constants = v.get("constants", {})

        # Build inputs struct
        inputs_dict = {}
        if isinstance(input_types, dict):
            for param_name, type_name in input_types.items():
                inputs_dict[param_name] = f"{type_name}()"
        # Add constants as scalar values
        for k, val in constants.items():
            inputs_dict[k] = _format_matlab_value(val)

        inputs_str = _format_matlab_struct(inputs_dict)
        outputs_str = f"{{{output_type}()}}" if output_type else "{}"

        # Build schema kwargs
        iterate_keys = schema_level if schema_level else schema_keys
        schema_str = _format_schema_kwargs(
            iterate_keys, schema_filter, constants, function_name
        )

        lines.append("% Run")
        lines.append(f"scihist.for_each(@{function_name}, ...")
        lines.append(f"    {inputs_str}, ...")
        if schema_str:
            lines.append(f"    {outputs_str}, ...")
            lines.append(f"    {schema_str});")
        else:
            lines.append(f"    {outputs_str});")
        lines.append("")

    return "\n".join(lines)


def _escape_matlab_string(s: str) -> str:
    """Escape single quotes for MATLAB string literals."""
    return s.replace("'", "''")


def _format_matlab_value(val) -> str:
    """Format a Python value as a MATLAB literal."""
    if isinstance(val, bool):
        return "true" if val else "false"
    if isinstance(val, int):
        return str(val)
    if isinstance(val, float):
        return str(val)
    if isinstance(val, str):
        return f"'{_escape_matlab_string(val)}'"
    if isinstance(val, (list, tuple)):
        elements = [_format_matlab_value(v) for v in val]
        return f"[{', '.join(elements)}]"
    return f"'{_escape_matlab_string(str(val))}'"


def _format_matlab_struct(inputs_dict: dict[str, str]) -> str:
    """Build a MATLAB ``struct(...)`` expression from a dict.

    Values are already formatted as MATLAB expressions (not quoted again).
    """
    if not inputs_dict:
        return "struct()"
    pairs = []
    for k, v in inputs_dict.items():
        pairs.append(f"'{k}', {v}")
    return f"struct({', '.join(pairs)})"


def _format_matlab_cell(items: list[str]) -> str:
    """Build a MATLAB cell array ``{Item1(), Item2()}``."""
    return "{" + ", ".join(items) + "}"


def _format_matlab_string_array(items: list[str]) -> str:
    """Format a Python list of strings as a MATLAB string array ``["a", "b"]``."""
    if not items:
        return "[]"
    escaped = [f'"{_escape_matlab_string(s)}"' for s in items]
    return "[" + ", ".join(escaped) + "]"


def _format_schema_kwargs(
    iterate_keys: list[str],
    schema_filter: dict[str, list] | None,
    constants: dict,
    function_name: str,
) -> str:
    """Build MATLAB name-value schema keyword arguments for for_each.

    Returns empty string if there are no schema arguments to pass.
    """
    if not iterate_keys:
        return ""

    parts = []
    for key in iterate_keys:
        if schema_filter and key in schema_filter and schema_filter[key]:
            values = schema_filter[key]
            # Format values: numbers as array, strings as string array.
            if all(isinstance(v, (int, float)) for v in values):
                formatted = "[" + " ".join(str(v) for v in values) + "]"
            else:
                formatted = _format_matlab_string_array([str(v) for v in values])
            parts.append(f"'{key}', {formatted}")

    if not parts:
        return ""
    return ", ".join(parts)
