"""
Code generation: a ``PlotSpec`` becomes readable seaborn/matplotlib source.

Export emits **literal plotting code**, not a call back into this package. The
alternative — ``return scistackplot.render(df, spec_path)`` — is more compact
and stays re-editable in the GUI, but it makes every exported pipeline depend
on this package at runtime and hides the figure's definition behind an opaque
call. Literal code matches the project's "minimize lock-in" goal and the
precedent in ``docs/claude/gui-export-to-plain-python.md``.

The spec is emitted as a docstring block so the GUI can round-trip it back out
of a file the user has since hand-edited.
"""

from __future__ import annotations

import json
import re

from .roles import complete_roles
from .shape import Shape
from .spec import ErrorBand, PlotKind, PlotSpec, Role, Statistic
from .table import LongTable

#: Marker delimiting the embedded spec inside a generated docstring.
SPEC_BEGIN = "scistackplot-spec:"

_SEABORN_ERRORBAR = {
    ErrorBand.SD: '"sd"',
    ErrorBand.SEM: '"se"',
    ErrorBand.CI95: '("ci", 95)',
    ErrorBand.IQR: '("pi", 50)',
    ErrorBand.NONE: "None",
}

_SERIES_COLUMN = "_series"


def generate_plot_function(
    spec: PlotSpec,
    table: LongTable,
    *,
    function_name: str | None = None,
) -> str:
    """
    Generate a ``plot_*`` function body for a scidb endpoint.

    The signature is ``(df, filename)`` — the shape scidb's ``plot_`` contract
    passes — and the function returns a Figure, which the framework saves to
    ``filename`` and closes.
    """
    name = function_name or default_function_name(spec)
    roles = complete_roles(spec, table)
    shape = table.shape_of(spec.y_measure)

    body: list[str] = []
    body.extend(_preamble(spec, table, roles, shape))
    body.extend(_plot_call(spec, table, roles, shape))

    lines = [
        f"def {name}(df, filename):",
        f'    """{_docstring(spec, table)}"""',
        "    import matplotlib.pyplot as plt",
        "    import pandas as pd",
        "    import seaborn as sns",
        "",
    ]
    lines.extend(f"    {line}" if line else "" for line in body)
    return "\n".join(lines) + "\n"


def default_function_name(spec: PlotSpec) -> str:
    """A valid ``plot_``-prefixed identifier derived from the measure name."""
    slug = re.sub(r"[^0-9a-zA-Z]+", "_", spec.y_measure).strip("_").lower()
    return f"plot_{slug or 'figure'}"


def extract_spec(source: str) -> PlotSpec | None:
    """
    Recover the embedded spec from generated source.

    Lets the GUI reopen a figure the user has since hand-edited: the code is
    the source of truth for rendering, the embedded spec only for repopulating
    the controls. Returns None when no spec is present.
    """
    start = source.find(SPEC_BEGIN)
    if start == -1:
        return None
    brace = source.find("{", start)
    if brace == -1:
        return None
    depth = 0
    for position in range(brace, len(source)):
        if source[position] == "{":
            depth += 1
        elif source[position] == "}":
            depth -= 1
            if depth == 0:
                try:
                    return PlotSpec.from_json(source[brace : position + 1])
                except (ValueError, KeyError):
                    return None
    return None


# ---------------------------------------------------------------------------


def _docstring(spec: PlotSpec, table: LongTable) -> str:
    iterate = spec.iterate_factors
    note = ""
    if iterate:
        note = (
            f"\n\n    One figure per {', '.join(iterate)} — these are the "
            f"for_each iteration keys, so they are NOT columns here."
        )
    if spec.facet.has_rules:
        note += (
            "\n\n    NOTE: the interactive layout arranged the subplots by "
            "matching\n    rules, which seaborn cannot express — this code "
            "wraps them in order\n    instead. The spec below still carries "
            "the rules."
        )
    return (
        f"{spec.kind} of {spec.y_measure}. Generated by scistackplot.{note}\n\n"
        f"    {SPEC_BEGIN}\n    {spec.to_json(indent=None)}\n    "
    )


def _preamble(spec, table, roles, shape) -> list[str]:
    """Melt, filters, 1-D explosion, aggregation — the order resolve() uses."""
    lines: list[str] = []

    # A dict/struct variable arrives at the endpoint as one column per field
    # (scidb's multi_column storage). The interactive path melts it in
    # ScidbSource.get_table, so the generated code has to melt it too — the
    # exported figure must be the previewed figure.
    for field in table.field_factors:
        levels = [str(level) for level in field.levels]
        lines.extend(
            [
                f"# one row per field of {spec.y_measure} "
                f"({len(levels)} field(s))",
                f"_fields = {levels!r}",
                "df = df.melt(",
                "    id_vars=[c for c in df.columns if c not in _fields],",
                "    value_vars=_fields,",
                f"    var_name={field.name!r},",
                f"    value_name={spec.y_measure!r},",
                ")",
                "",
            ]
        )

    filter_lines: list[str] = []
    for flt in spec.filters:
        if flt.include is not None:
            filter_lines.append(f"df = df[df[{flt.column!r}].isin({list(flt.include)!r})]")
        if flt.exclude is not None:
            filter_lines.append(f"df = df[~df[{flt.column!r}].isin({list(flt.exclude)!r})]")
        if flt.minimum is not None:
            filter_lines.append(f"df = df[df[{flt.column!r}] >= {flt.minimum!r}]")
        if flt.maximum is not None:
            filter_lines.append(f"df = df[df[{flt.column!r}] <= {flt.maximum!r}]")
    if filter_lines:
        lines.extend([*filter_lines, ""])

    index_column = spec.index_column or table.index_column or "index"
    if shape is Shape.SERIES_1D and not table.measure(spec.y_measure).exploded:
        y = spec.y_measure
        lines.extend(
            [
                "# 1-D measure: one row per sample",
                f"df[{index_column!r}] = df[{y!r}].map(lambda v: list(range(len(v))))",
                f"df = df.explode([{y!r}, {index_column!r}], ignore_index=True)",
                f"df[{y!r}] = pd.to_numeric(df[{y!r}])",
                f"df[{index_column!r}] = pd.to_numeric(df[{index_column!r}])",
                "",
            ]
        )

    aggregated = [name for name, role in roles.items() if role is Role.AGGREGATE]
    if aggregated:
        keep = [
            name
            for name, role in roles.items()
            if role not in (Role.AGGREGATE, Role.ITERATE)
        ]
        if shape is Shape.SERIES_1D:
            keep.append(index_column)
        lines.extend(
            [
                f"# average over {', '.join(aggregated)}",
                f"df = df.groupby({keep!r}, as_index=False)[{spec.y_measure!r}].mean()",
                "",
            ]
        )

    if spec.kind is PlotKind.LINE:
        series_cols = [
            name
            for name, role in roles.items()
            if role not in (Role.ITERATE, Role.AGGREGATE)
            and name != _role_holder(roles, Role.X)
        ]
        if series_cols:
            lines.extend(
                [
                    "# one line per observation",
                    f"df[{_SERIES_COLUMN!r}] = "
                    f"df[{series_cols!r}].astype(str).agg(' | '.join, axis=1)",
                    "",
                ]
            )

    return lines


def _plot_call(spec, table, roles, shape) -> list[str]:
    if shape is Shape.MATRIX_2D:
        return _heatmap_call(spec)

    kind = spec.kind
    x = _x_expression(spec, table, roles, shape)
    color = _role_holder(roles, Role.COLOR)
    facets = [name for name, role in roles.items() if role is Role.FACET]

    args = [f"data=df", f"x={x!r}", f"y={spec.y_measure!r}"]
    if color:
        args.append(f"hue={color!r}")
    # seaborn takes one factor per grid axis: the first faceted factor drives
    # the columns, a second one the rows. A rule-defined layout
    # (FacetOptions.rows/cols) has no seaborn equivalent, so the generated code
    # falls back to a wrapped flow and says so.
    if facets:
        args.append(f"col={facets[0]!r}")
    if len(facets) > 1:
        args.append(f"row={facets[1]!r}")
    if facets and len(facets) == 1 and spec.facet.wrap:
        args.append(f"col_wrap={spec.facet.wrap}")

    estimator = (
        '"median"' if spec.aggregate.statistic is Statistic.MEDIAN else '"mean"'
    )
    errorbar = _SEABORN_ERRORBAR[spec.aggregate.error]

    if kind in (PlotKind.BOX, PlotKind.VIOLIN, PlotKind.BAR, PlotKind.STRIP):
        seaborn_kind = {
            PlotKind.BOX: "box",
            PlotKind.VIOLIN: "violin",
            PlotKind.BAR: "bar",
            PlotKind.STRIP: "strip",
        }[kind]
        args.append(f'kind="{seaborn_kind}"')
        if kind is PlotKind.BAR:
            args.append(f"estimator={estimator}")
            args.append(f"errorbar={errorbar}")
        call = "sns.catplot"
    elif kind is PlotKind.SCATTER:
        if _x_is_categorical(spec, table, roles, shape):
            args.extend(['kind="strip"', "jitter=False"])
            call = "sns.catplot"
        else:
            args.append('kind="scatter"')
            call = "sns.relplot"
    elif kind is PlotKind.LINE:
        args.append('kind="line"')
        args.append("estimator=None")
        if any(role is Role.FREE for role in roles.values()):
            args.append(f"units={_SERIES_COLUMN!r}")
        call = "sns.relplot"
    elif kind is PlotKind.BAND:
        args.extend([f'kind="line"', f"estimator={estimator}", f"errorbar={errorbar}"])
        call = "sns.relplot"
    else:  # pragma: no cover - every kind is covered above
        args.append('kind="scatter"')
        call = "sns.relplot"

    style = spec.style
    if style.palette:
        args.append(f"palette={style.palette!r}")

    lines = [f"g = {call}(", *[f"    {arg}," for arg in args], ")"]
    lines.append(
        f"g.set_axis_labels({(style.x_label or x)!r}, "
        f"{(style.y_label or spec.y_measure)!r})"
    )
    if style.log_x:
        lines.append('g.set(xscale="log")')
    if style.log_y:
        lines.append('g.set(yscale="log")')
    if style.title:
        lines.append(f"g.figure.suptitle({style.title!r})")
    lines.append(f"g.figure.set_size_inches({style.width}, {style.height})")
    lines.append("return g.figure")
    return lines


def _heatmap_call(spec) -> list[str]:
    return [
        "import numpy as np",
        "",
        f"matrix = np.mean(np.stack([np.asarray(v, dtype=float) "
        f"for v in df[{spec.y_measure!r}]]), axis=0)",
        f"fig, ax = plt.subplots(figsize=({spec.style.width}, {spec.style.height}))",
        'image = ax.imshow(matrix, aspect="auto", origin="lower")',
        "fig.colorbar(image, ax=ax)",
        f"ax.set_title({(spec.style.title or spec.y_measure)!r})",
        "return fig",
    ]


def _x_expression(spec, table, roles, shape) -> str:
    if spec.x_measure:
        return spec.x_measure
    if shape is Shape.SERIES_1D:
        return spec.index_column or table.index_column or "index"
    holder = _role_holder(roles, Role.X)
    return holder or (table.factor_names[0] if table.factors else "index")


def _x_is_categorical(spec, table, roles, shape) -> bool:
    if spec.x_measure or shape is Shape.SERIES_1D:
        return False
    return _role_holder(roles, Role.X) is not None


def _role_holder(roles: dict[str, Role], role: Role) -> str | None:
    for name, assigned in roles.items():
        if assigned is role:
            return name
    return None


def generate_script(
    spec: PlotSpec,
    table: LongTable,
    *,
    source_expression: str = 'pd.read_csv("data.csv")',
    function_name: str | None = None,
) -> str:
    """
    A complete runnable script — the standalone (no scidb) export.

    Same generated function, plus the few lines that load a table and save the
    figure, so a CSV user gets something they can run immediately.
    """
    name = function_name or default_function_name(spec)
    function = generate_plot_function(spec, table, function_name=name)
    return (
        '"""Generated by scistackplot."""\n'
        "import matplotlib.pyplot as plt\n"
        "import pandas as pd\n"
        "import seaborn as sns\n\n\n"
        f"{function}\n\n"
        'if __name__ == "__main__":\n'
        f"    df = {source_expression}\n"
        f'    figure = {name}(df, "figure.png")\n'
        '    figure.savefig("figure.png", dpi=150, bbox_inches="tight")\n'
    )


def spec_json_block(spec: PlotSpec) -> str:
    """The spec as a pretty JSON block, for writing next to generated code."""
    return json.dumps(spec.to_dict(), indent=2, sort_keys=True)
